name: hc_opioid
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.23.5
  - seaborn=0.12.2
  - matplotlib=3.6.2
  - notebook=6.5.4
  - jupyterlab=3.6.3
  - jupyter_core=5.3.0
  - numba=0.57.1
  - pandas=1.5.3
  - pip=23.2.1
  - scikit-learn=1.3.2
  - openpyxl=3.0.10
  - pytest=7.4.0
  - pytest-mock=3.10.0
  - pip:
      - ydata_profiling==4.5.1
      - lime==0.2.0.1
      - shap==0.42.1
      - witwidget==1.8.1
      - wandb==0.18.7
