wandb_version: 1

C:
  desc: null
  value: 0.1
class_weight:
  desc: null
  value: null
max_iter:
  desc: null
  value: 300
penalty:
  desc: null
  value: l1
solver:
  desc: null
  value: liblinear
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.12
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1698327882.192111
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.9.18
      5: 0.15.12
      8:
      - 1
      - 5
      13: linux-x86_64
