wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.12
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1698188047.914063
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.9.18
      5: 0.15.12
      8:
      - 1
      - 5
      13: linux-x86_64
    viz:
      elbow_curve:
        id: wandb/elbow/v1
        historyFieldSettings:
          x-axis: _step
          key: elbow_curve
      silhouette_plot:
        id: wandb/silhouette_/v1
        historyFieldSettings:
          x-axis: _step
          key: silhouette_plot
