wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.11
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1698183646.589365
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.9.18
      5: 0.15.11
      8:
      - 1
      - 5
      10:
      - 5
      13: linux-x86_64
    viz:
      class_proportions:
        id: wandb/class_proportions/v1
        historyFieldSettings:
          x-axis: _step
          key: class_proportions
      learning_curve:
        id: wandb/learning_curve/v1
        historyFieldSettings:
          x-axis: _step
          key: learning_curve
      roc:
        id: wandb/roc/v1
        historyFieldSettings:
          x-axis: _step
          key: roc
      precision_recall:
        id: wandb/pr_curve/v1
        historyFieldSettings:
          x-axis: _step
          key: precision_recall
      feature_importances:
        id: wandb/feature_importances/v1
        historyFieldSettings:
          x-axis: _step
          key: feature_importances
      confusion_matrix:
        id: wandb/confusion_matrix/v1
        historyFieldSettings:
          x-axis: _step
          key: confusion_matrix
      summary_metrics:
        id: wandb/metrics/v1
        historyFieldSettings:
          x-axis: _step
          key: summary_metrics
      calibration_curve:
        id: wandb/calibration/v1
        historyFieldSettings:
          x-axis: _step
          key: calibration_curve
