wandb_version: 1

alpha:
  desc: null
  value: 1.0
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.12
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1698266522.388386
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.9.18
      5: 0.15.12
      8:
      - 1
      - 5
      13: linux-x86_64
    viz:
      residuals:
        id: wandb/residuals_plot/v1
        historyFieldSettings:
          x-axis: _step
          key: residuals
      outlier_candidates:
        id: wandb/outliers/v1
        historyFieldSettings:
          x-axis: _step
          key: outlier_candidates
      summary_metrics:
        id: wandb/metrics/v1
        historyFieldSettings:
          x-axis: _step
          key: summary_metrics
      learning_curve:
        id: wandb/learning_curve/v1
        historyFieldSettings:
          x-axis: _step
          key: learning_curve
